composer: allow PHP 8.0
Jean85/pretty-package-versions pull request #25
Opened 2020-08-31 00:02 UTC by TomasVotruba

2020-09-01 12:59 UTC, Jean85 requested changes
Thank you for your contribution! Could you please add PHP 8 in the CI matrix to test it out?

2020-09-06 13:49 UTC, TomasVotruba commented
Sure

2020-09-06 15:03 UTC, TomasVotruba commented
What's the current PHP on travis?

I'm used to Github Actions last year and there the version works fine.
Would consider switching to Github Actoins? I can handle it

2020-09-07 09:53 UTC, Jean85 commented
Happy to accept a (separate) PR that migrates to GitHub Actions, I never used them so I don't know where to start.

2020-09-07 15:47 UTC, TomasVotruba commented on .github/workflows/tests.yaml
> +                php: ['7.0', '7.1', '7.2', '7.3', '7.4', '8.0']
Btw, what about bumping min PHP version? PHP 7.1 and lower are dangerous to use - https://www.php.net/supported-versions.php

Also, package will be still available for the older PHP versions with version 1.5, so there is no BC break

2020-09-07 15:48 UTC, TomasVotruba commented
Ah, just saw *separate* word (brackets)

I'll make a new PR

2020-09-07 15:49 UTC, TomasVotruba commented
There it is: https://github.com/Jean85/pretty-package-versions/pull/26

After that gets merged, I'll rebase this PR

2020-09-07 16:15 UTC, Jean85 commented
#26 merged and migration is completed thanks to #27. Thank you for your help! Now you can rebase...

2020-09-07 23:34 UTC, TomasVotruba commented
Rebased... it seems PHPUnit is the problem:

![image](https://user-images.githubusercontent.com/924196/92420397-6702ef00-f173-11ea-9ad5-63d8bc38abab.png)

2020-09-13 19:51 UTC, Jean85 commented
It's not PHPUnit but Prophecy specifically: https://github.com/phpspec/prophecy/issues/491

2020-09-13 20:11 UTC, TomasVotruba commented
Yea, fractal of bad version design :/

Could you merge this, as it's only dev dependency and unrelated to version?

I had to fork this package, as I needed to continue upgrading to PHP 8.

I'd prefer to use original code though.

2020-09-14 08:00 UTC, Jean85 commented
Closing in favor of #28

2020-09-14 08:00 UTC, closed without merging

2020-09-14 08:46 UTC, TomasVotruba commented
Nice detailed CI checks :+1: 

Thank you