NO_REFERENCE_TEXT in  Version::NO_REFERENCE_TEXT
Jean85/pretty-package-versions pull request #38
Opened 2021-02-05 13:03 UTC by DeyV

Text ``` '{no reference}' ``` is strange, and  {  }  make usage of output from this function not usable in many scopes (for example url with hash). 

Especially strange is when is is parsed by getShortReference()  =>  ``` {no ref ``` 

My suggest is change this behavior in future releases. But for now - this should help fix it in user scope.

2021-02-21 09:11 UTC, DeyV commented
@Jean85 please review

2021-02-22 10:16 UTC, Jean85 requested changes

2021-02-22 10:16 UTC, Jean85 commented on src/Version.php
> +    const NO_REFERENCE_TEXT = '{no reference}';
We now require 7.1, so we can make the visibility explicit: 
```suggestion
    public const NO_REFERENCE_TEXT = '{no reference}';
```

2021-02-22 10:49 UTC, Jean85 approved these changes

2021-02-22 10:50 UTC, merged

2021-02-22 10:50 UTC, Jean85 commented
Thank you!