Deprecate InstalledVersions::getRawData
Jean85/pretty-package-versions pull request #39
Opened 2021-05-24 11:19 UTC by BramRoets

Composer released an [update](https://getcomposer.org/changelog/2.0.14) that deprecates the `getRawData()` method.

This PR uses the new recommended `getAllRawData()` method.

This package is used by https://github.com/getsentry/sentry-php. After a recent deployment, Sentry stopped working because of the change made by composer. I hope to get this PR merged and then update the requirement in Sentry.

Related commit in Composer: https://github.com/composer/composer/pull/9816/files

2021-05-24 12:39 UTC, Jean85 requested changes
Thanks for the heads up, it's nice to tackle this head on.

I'm sorry but this PR is not feasible in this form. `getAllRawData` is present only since the commit you listed, and hence it would break under any Composer between 2.0.0 and 2.0.13.

The only way around this that I see is to check for method existence.

2021-05-24 12:52 UTC, BramRoets commented
@Jean85 Thanks, that makes sense! Let me know if it needs any additional changes.

2021-05-24 16:04 UTC, Jean85 approved these changes
The code looks fine, thanks!

I was going to propose an optimization, but I just only noticed that you're dealing with N possible entries with this change, so no optimization is doable...

I would like to cover this with tests but I don't think it will be doable :( Damn

2021-05-24 16:08 UTC, Jean85 commented
I've approved the CI, it's complaining because it doesn't recognize the method... I don't understand why, probably composer in CI is older than the requested patch?

Maybe we can downgrade Composer in the `--prefer-lowest` job to cover both cases?

2021-05-25 06:22 UTC, BramRoets commented
I've added some additional steps to the tests. Not sure if this will fix them. Can you approve the GitHub Action?

2021-05-25 07:02 UTC, Jean85 commented
@BramRoets I reworked the CI flow, since it had complications from when 8.0 wasn't stable. I also found a way to solve the Composer version constraint using `setup-php`.

I'll also check the PHPStan issue.

2021-05-25 07:23 UTC, Jean85 requested changes
PHPStan doesn't budge, I don't know why it doesn't recognize the presence of that method, neither the existence check. 

Please put that in the baseline to fix the CI, and add a changelog entry for this PR, then it's good to merge.

2021-05-25 16:51 UTC, BramRoets commented
Hi Jean, I'm not sure. Do you need any input from my side?

2021-05-26 07:08 UTC, umbarov commented
Hi,
will this PR be merged? Composer broke half of the web with it's deprecation. Do you need some help? And thank you for your work 👍

2021-05-26 08:47 UTC, merged

2021-05-26 08:51 UTC, Jean85 commented
I had to manually merge this since I couldn't push this from local, don't know why. Thanks anyway @BramRoets!

This has been released as 2.0.4: https://github.com/Jean85/pretty-package-versions/releases/tag/2.0.4

2021-05-26 09:43 UTC, software-artificer commented
Thanks a lot for quick turnaround 🙇🏻‍♂️ What are the chances that this will be backported to 1.6.x branch?

2021-05-26 11:07 UTC, Jean85 commented
@filakhtov this issue does not affect 1.6 because I do not use the Composer API directly there, but I use `composer/package-versions-deprecated` there. So in that case the issue is fixed by https://github.com/composer/package-versions-deprecated/pull/25